INSERT INTO genre (nom_genre, type_genre) VALUES
('Homme', 'cisgenre'),
('Homme', 'transgenre'),
('Femme', 'cisgenre'),
('Femme', 'transgenre'),
('Non-binaire', 'cisgenre'),
('Non-binaire', 'transgenre'),
('Genre fluide', 'cisgenre'),
('Genre fluide', 'transgenre'),
('Agenre', 'cisgenre'),
('Agenre', 'transgenre'),
('Bigender', 'cisgenre'),
('Bigender', 'transgenre'),
('Demigenre homme', 'cisgenre'),
('Demigenre homme', 'transgenre'),
('Demigenre femme', 'cisgenre'),
('Demigenre femme', 'transgenre'),
('Androgyne', 'cisgenre'),
('Androgyne', 'transgenre'),
('Genderqueer', 'cisgenre'),
('Genderqueer', 'transgenre'),
('Two-Spirit', 'cisgenre'),
('Two-Spirit', 'transgenre'),
('Neutrois', 'cisgenre'),
('Neutrois', 'transgenre'),
('Agenre', 'agenre'),
('Non-binaire', 'non spécifié');


INSERT INTO orientation (nom_orientation, description_orientation) VALUES
('Hétérosexuel', 'Attirance sexuelle et/ou romantique envers des personnes du sexe opposé.'),
('Homosexuel', 'Attirance sexuelle et/ou romantique envers des personnes du même sexe.'),
('Bisexuel', 'Attirance sexuelle et/ou romantique envers des personnes de deux sexes ou genres.'),
('Pansexuel', 'Attirance sexuelle et/ou romantique envers des personnes indépendamment de leur genre.'),
('Asexuel', 'Absence d’attirance sexuelle envers autrui.'),
('Demi-sexuel', 'Attirance sexuelle qui ne se manifeste qu’après un fort lien émotionnel.'),
('Queer', 'Orientation non normative, souvent utilisée pour indiquer une attirance hors des catégories traditionnelles.'),
('Sapiosexuel', 'Attirance sexuelle principalement basée sur l’intelligence.'),
('Graysexuel', 'Attirance sexuelle rare ou faible.'),
('Androsexuel', 'Attirance sexuelle envers les hommes ou les masculinités.'),
('Gynosexuel', 'Attirance sexuelle envers les femmes ou les féminités.'),
('Polysexuel', 'Attirance sexuelle envers plusieurs genres, mais pas tous.'),
('Skoliosexuel', 'Attirance sexuelle envers les personnes non-binaires ou transgenres.'),
('Hétéroflexible', 'Principalement attiré par le sexe opposé, avec quelques exceptions.'),
('Homoflexible', 'Principalement attiré par le même sexe, avec quelques exceptions.'),
('Autosexuel', 'Attirance sexuelle envers soi-même.'),
('Lithsexuel', 'Attirance sexuelle sans désir de réciprocité.'),
('Abrosexuel', 'Orientation sexuelle fluide, changeante dans le temps.'),
('Pomosexuel', 'Rejet des catégories traditionnelles d’orientation sexuelle.'),
('Fraysexuel', 'Attirance sexuelle qui diminue avec la connaissance accrue de la personne.'),
('Reciprosexuel', 'Attirance sexuelle uniquement si elle est réciproque.'),
('Hétérocurieux', 'Curiosité envers l’attirance pour le sexe opposé.'),
('Homocurieux', 'Curiosité envers l’attirance pour le même sexe.');

INSERT INTO tag (nom, categorie_tag) VALUES
-- Emotions
('Heureux', 'Emotion'),
('Triste', 'Emotion'),
('Anxieux', 'Emotion'),
('Calme', 'Emotion'),
('Excité', 'Emotion'),
('Nostalgique', 'Emotion'),
('Énergique', 'Emotion'),
('Stressé', 'Emotion'),
('Motivé', 'Emotion'),
('Déprimé', 'Emotion'),

-- Lieux
('Paris', 'Lieu'),
('Montagne', 'Lieu'),
('Plage', 'Lieu'),
('Forêt', 'Lieu'),
('Ville', 'Lieu'),
('Campagne', 'Lieu'),
('Désert', 'Lieu'),
('Lac', 'Lieu'),
('Rivière', 'Lieu'),
('Parc', 'Lieu'),

-- Activités
('Randonnée', 'Activité'),
('Lecture', 'Activité'),
('Cuisine', 'Activité'),
('Yoga', 'Activité'),
('Natation', 'Activité'),
('Voyage', 'Activité'),
('Musique', 'Activité'),
('Danse', 'Activité'),
('Jeux vidéo', 'Activité'),
('Photographie', 'Activité'),

-- Genres
('Cisgenre homme', 'Genre'),
('Cisgenre femme', 'Genre'),
('Non-binaire', 'Genre'),
('Genderfluid', 'Genre'),
('Transgenre homme', 'Genre'),
('Transgenre femme', 'Genre'),
('Agender', 'Genre'),
('Bigender', 'Genre'),
('Demigenre', 'Genre'),
('Pangender', 'Genre'),

-- Orientations
('Hétérosexuel', 'Orientation'),
('Homosexuel', 'Orientation'),
('Bisexuel', 'Orientation'),
('Pansexuel', 'Orientation'),
('Asexuel', 'Orientation'),
('Queer', 'Orientation'),
('Demi-sexuel', 'Orientation'),
('Sapiosexuel', 'Orientation'),
('Polysexuel', 'Orientation'),
('Graysexuel', 'Orientation'),

-- Couleurs
('Bleu', 'Couleur'),
('Vert', 'Couleur'),
('Rouge', 'Couleur'),
('Noir', 'Couleur'),
('Blanc', 'Couleur'),
('Jaune', 'Couleur'),
('Violet', 'Couleur'),
('Orange', 'Couleur'),
('Marron', 'Couleur'),
('Rose', 'Couleur'),

--Musique
('Hit Me Hard And Soft', 'Musique'),
('Your Teeth In My Neck', 'Musique'),
('Me and Your Mama', 'Musique'),
('Between The Cheeks', 'Musique'),
('Sossaup', 'Musique'),
('Best For Me', 'Musique'),
('Girls Just Want To Have Fun', 'Musique'),
('IFHY', 'Musique'),
('Know Love', 'Musique'),
('911/Mr. Lonely', 'Musique'),


--Autres
('DENIAL IS A RIVER', 'Autres'),
('WAIT A MINUTE', 'Autres'),
('Si una Vez', 'Autres'),
('Some Girl', 'Autres'),
('BIRDS OF A FEATHER', 'Autres'),
('PRIDE.', 'Autres'),
('the perfect pair', 'Autres'),
('C U Girl', 'Autres'),
('Infrunami', 'Autres');